### ISSUE TITLE
need requirements file!

### ISSUE THREAD

**Issue by ahsanMuh** [Kojk-AI/deepstream-face-recognition#1]
Hi there!

I would first of all like to appreciate the great work you have done. Also, I would like to add that I have not started the work right now but I plan to do it starting tomorrow. 

Please confirm that the jupyter notebook to get the embeddings is meant to be run on PC (not jetson), right? Inferring this as it seems that you are also running the apps headless.

Another concern is, can you please provide a requirement file for the notebook?

Thank you so much

**Comment by Kojk-AI** [comment]
Requirements file have been provided. Attached as well for your convenience.
[requirements.txt](https://github.com/Kojk-AI/deepstream-face-recognition/files/9670578/requirements.txt)
