### ISSUE TITLE
Error in transposing face array

### ISSUE THREAD

**Issue by kitanoyoru** [Kojk-AI/deepstream-face-recognition#2]
Hi there!

I have an error in [modify_keras_FaceNet.ipynb](https://github.com/Kojk-AI/deepstream-face-recognition/blob/main/notebooks/modify_keras_FaceNet.ipynb) while transposing face right here:
```python3
  for face in images:
      face = cv2.imread(image)
      print(image)
      face = cv2.resize(face, (160,160))
      face = np.transpose(face, [0,3,1,2])
      face = np.expand_dims(face, 0)
      emb = model.predict(face)
      emb = l2_normalize(emb)
      embeddings.append(emb)
```

```bash
Traceback (most recent call last):
  File "/home/kitanoyoru/modify_facenet.py", line 366, in <module>
    face = np.transpose(face, [0,3,1,2])
  File "<__array_function__ internals>", line 180, in transpose
  File "/usr/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 660, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```
I have used images with Bill Gates from this repo https://github.com/nyoki-mtl/keras-facenet. Maybe error in image size or something like that, idk.

And why do we iterate the variable "face" in the for loop and not use it. Maybe this is correct:

```python3
  for image in images:             # change face to image here
      face = cv2.imread(image)
      print(image)
      face = cv2.resize(face, (160,160))
      face = np.transpose(face, [0,3,1,2])
      face = np.expand_dims(face, 0)
      emb = model.predict(face)
      emb = l2_normalize(emb)
      embeddings.append(emb)
```

**Comment by Kojk-AI** [comment]
> I have an error in [modify_keras_FaceNet.ipynb](https://github.com/Kojk-AI/deepstream-face-recognition/blob/main/notebooks/modify_keras_FaceNet.ipynb) while transposing face right here:

I'm sorry. This is my mistake. The np.tranpose() was supposedly to be after the np.expand_dims(). Before the expand dims function, it has only 3 axis, therefore the transpose function (with an argument of size 4) couldn't work. Another way is to change the argument from [0,3,1,2] to [2,0,1]. (which is now implemented)

> And why do we iterate the variable "face" in the for loop and not use it. Maybe this is correct:

You are right. Correction have been made.
